---

# Determine architecture and suffix
- name: Check for amd64 architecture
  set_fact:
    k3s_arch: "amd64"
    k3s_suffix: ""
  when: ansible_facts.architecture == "x86_64" or
        ansible_facts.architecture == "amd64"

- name: Check for arm64 architecture
  set_fact:
    k3s_arch: "arm64"
    k3s_suffix: "-arm64"
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Check for arm architecture
  set_fact:
    k3s_arch: "arm"
    k3s_suffix: "-armhf"
  when:
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"

# Determine version to download
- name: Determine version from channel
  vars:
    version_url: "{{ k3s_channel_url }}/{{ k3s_channel }}"
  shell: "curl -w '%{url_effective}' -L -s -S {{ version_url }} -o /dev/null | sed -e 's|.*/||'"
  register: curl_output
  when: k3s_version == 'undefined'
  run_once: true

- name: Output channel information
  debug:
    msg:
      - "k3s_channel_url: {{ k3s_channel_url }}"
      - "k3s_channel: {{ k3s_channel }}"
  when: k3s_version == 'undefined'
  run_once: true

- name: Set version from channel
  set_fact:
    k3s_version: "{{ curl_output.stdout_lines[0] }}"
  when: k3s_version == 'undefined'
  run_once: true

- name: Output version
  debug:
    msg: "k3s_version: {{ k3s_version }}"
  run_once: true

# Set binary and hash file URLs
- name: Determine GitHub URLs
  set_fact:
    binary_url: "{{ github_url }}/download/{{ k3s_version }}/k3s{{ k3s_suffix }}"
    hash_url:   "{{ github_url }}/download/{{ k3s_version }}/sha256sum-{{ k3s_arch }}.txt"
  when: k3s_commit == 'undefined'

- name: Determine Storage URLs
  set_fact:
    binary_url: "{{ storage_url }}/k3s{{ k3s_suffix }}-{{ install_k3s_commit }}"
    hash_url:   "{{ storage_url }}/k3s{{ k3s_suffix }}-{{ install_k3s_commit }}.sha256sum"
  when: k3s_commit != 'undefined'

- name: Download k3s binary
  get_url:
    url: "{{ binary_url }}"
    checksum: "sha256:{{ hash_url }}"
    dest: "{{ bin_dir }}/k3s"
    owner: root
    group: root
    mode: 0755

