---

# See README.md for more options

# This is the user that has SSH password-less access to configure your hosts
ansible_user: debian

# The location of where to capture the kube config of the new cluster
cluster_config: cluster.conf

# Use the latest version
install_k3s_channel: 'latest'

# Flags for the k3s executable
install_k3s_server_args: ''
install_k3s_agent_args: ''

