---
k3s_version: v1.22.3+k3s1
ansible_user: debian
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

k3s_server_location: /var/lib/rancher/k3s

# Services information
systemd_dir: /etc/systemd/system

k3s_services:
  - k3s
  - k3s-node

k3s_service_file_extensions:
  - service
  - service.env

